/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/WezQ-text.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <directionalLight intensity={0.7} decay={2} position={[5, 10, 7.5]} />
      <mesh 
        geometry={nodes['3D-text-WezQstl'].geometry} 
        material={nodes['3D-text-WezQstl'].material}
        position={[1, 0, 0]}
        scale={3.5}
        rotation={[0.3, 0.28, 0]}
        />
    </group>
  )
}

useGLTF.preload('/WezQ-text.gltf')
